#pragma once

#include "cat.h"

#define PP_REPEAT(n, m, d) PP_CAT(PP_REPEAT_, n)(m, d)

#define PP_REPEAT_0(m, d)
#define PP_REPEAT_1(m, d) m(d, 0)
#define PP_REPEAT_2(m, d) PP_REPEAT_1(m, d) m(d, 1)
#define PP_REPEAT_3(m, d) PP_REPEAT_2(m, d) m(d, 2)
#define PP_REPEAT_4(m, d) PP_REPEAT_3(m, d) m(d, 3)
#define PP_REPEAT_5(m, d) PP_REPEAT_4(m, d) m(d, 4)
#define PP_REPEAT_6(m, d) PP_REPEAT_5(m, d) m(d, 5)
#define PP_REPEAT_7(m, d) PP_REPEAT_6(m, d) m(d, 6)
#define PP_REPEAT_8(m, d) PP_REPEAT_7(m, d) m(d, 7)
#define PP_REPEAT_9(m, d) PP_REPEAT_8(m, d) m(d, 8)
#define PP_REPEAT_10(m, d) PP_REPEAT_9(m, d) m(d, 9)
#define PP_REPEAT_11(m, d) PP_REPEAT_10(m, d) m(d, 10)
#define PP_REPEAT_12(m, d) PP_REPEAT_11(m, d) m(d, 11)
#define PP_REPEAT_13(m, d) PP_REPEAT_12(m, d) m(d, 12)
#define PP_REPEAT_14(m, d) PP_REPEAT_13(m, d) m(d, 13)
#define PP_REPEAT_15(m, d) PP_REPEAT_14(m, d) m(d, 14)
#define PP_REPEAT_16(m, d) PP_REPEAT_15(m, d) m(d, 15)
#define PP_REPEAT_17(m, d) PP_REPEAT_16(m, d) m(d, 16)
#define PP_REPEAT_18(m, d) PP_REPEAT_17(m, d) m(d, 17)
#define PP_REPEAT_19(m, d) PP_REPEAT_18(m, d) m(d, 18)
#define PP_REPEAT_20(m, d) PP_REPEAT_19(m, d) m(d, 19)
#define PP_REPEAT_21(m, d) PP_REPEAT_20(m, d) m(d, 20)
#define PP_REPEAT_22(m, d) PP_REPEAT_21(m, d) m(d, 21)
#define PP_REPEAT_23(m, d) PP_REPEAT_22(m, d) m(d, 22)
#define PP_REPEAT_24(m, d) PP_REPEAT_23(m, d) m(d, 23)
#define PP_REPEAT_25(m, d) PP_REPEAT_24(m, d) m(d, 24)
#define PP_REPEAT_26(m, d) PP_REPEAT_25(m, d) m(d, 25)
#define PP_REPEAT_27(m, d) PP_REPEAT_26(m, d) m(d, 26)
#define PP_REPEAT_28(m, d) PP_REPEAT_27(m, d) m(d, 27)
#define PP_REPEAT_29(m, d) PP_REPEAT_28(m, d) m(d, 28)
#define PP_REPEAT_30(m, d) PP_REPEAT_29(m, d) m(d, 29)
#define PP_REPEAT_31(m, d) PP_REPEAT_30(m, d) m(d, 30)
#define PP_REPEAT_32(m, d) PP_REPEAT_31(m, d) m(d, 31)
#define PP_REPEAT_33(m, d) PP_REPEAT_32(m, d) m(d, 32)
#define PP_REPEAT_34(m, d) PP_REPEAT_33(m, d) m(d, 33)
#define PP_REPEAT_35(m, d) PP_REPEAT_34(m, d) m(d, 34)
#define PP_REPEAT_36(m, d) PP_REPEAT_35(m, d) m(d, 35)
#define PP_REPEAT_37(m, d) PP_REPEAT_36(m, d) m(d, 36)
#define PP_REPEAT_38(m, d) PP_REPEAT_37(m, d) m(d, 37)
#define PP_REPEAT_39(m, d) PP_REPEAT_38(m, d) m(d, 38)
#define PP_REPEAT_40(m, d) PP_REPEAT_39(m, d) m(d, 39)
#define PP_REPEAT_41(m, d) PP_REPEAT_40(m, d) m(d, 40)
#define PP_REPEAT_42(m, d) PP_REPEAT_41(m, d) m(d, 41)
#define PP_REPEAT_43(m, d) PP_REPEAT_42(m, d) m(d, 42)
#define PP_REPEAT_44(m, d) PP_REPEAT_43(m, d) m(d, 43)
#define PP_REPEAT_45(m, d) PP_REPEAT_44(m, d) m(d, 44)
#define PP_REPEAT_46(m, d) PP_REPEAT_45(m, d) m(d, 45)
#define PP_REPEAT_47(m, d) PP_REPEAT_46(m, d) m(d, 46)
#define PP_REPEAT_48(m, d) PP_REPEAT_47(m, d) m(d, 47)
#define PP_REPEAT_49(m, d) PP_REPEAT_48(m, d) m(d, 48)
#define PP_REPEAT_50(m, d) PP_REPEAT_49(m, d) m(d, 49)
#define PP_REPEAT_51(m, d) PP_REPEAT_50(m, d) m(d, 50)
#define PP_REPEAT_52(m, d) PP_REPEAT_51(m, d) m(d, 51)
#define PP_REPEAT_53(m, d) PP_REPEAT_52(m, d) m(d, 52)
#define PP_REPEAT_54(m, d) PP_REPEAT_53(m, d) m(d, 53)
#define PP_REPEAT_55(m, d) PP_REPEAT_54(m, d) m(d, 54)
#define PP_REPEAT_56(m, d) PP_REPEAT_55(m, d) m(d, 55)
#define PP_REPEAT_57(m, d) PP_REPEAT_56(m, d) m(d, 56)
#define PP_REPEAT_58(m, d) PP_REPEAT_57(m, d) m(d, 57)
#define PP_REPEAT_59(m, d) PP_REPEAT_58(m, d) m(d, 58)
#define PP_REPEAT_60(m, d) PP_REPEAT_59(m, d) m(d, 59)
#define PP_REPEAT_61(m, d) PP_REPEAT_60(m, d) m(d, 60)
#define PP_REPEAT_62(m, d) PP_REPEAT_61(m, d) m(d, 61)
#define PP_REPEAT_63(m, d) PP_REPEAT_62(m, d) m(d, 62)
#define PP_REPEAT_64(m, d) PP_REPEAT_63(m, d) m(d, 63)
#define PP_REPEAT_65(m, d) PP_REPEAT_64(m, d) m(d, 64)
#define PP_REPEAT_66(m, d) PP_REPEAT_65(m, d) m(d, 65)
#define PP_REPEAT_67(m, d) PP_REPEAT_66(m, d) m(d, 66)
#define PP_REPEAT_68(m, d) PP_REPEAT_67(m, d) m(d, 67)
#define PP_REPEAT_69(m, d) PP_REPEAT_68(m, d) m(d, 68)
#define PP_REPEAT_70(m, d) PP_REPEAT_69(m, d) m(d, 69)
#define PP_REPEAT_71(m, d) PP_REPEAT_70(m, d) m(d, 70)
#define PP_REPEAT_72(m, d) PP_REPEAT_71(m, d) m(d, 71)
#define PP_REPEAT_73(m, d) PP_REPEAT_72(m, d) m(d, 72)
#define PP_REPEAT_74(m, d) PP_REPEAT_73(m, d) m(d, 73)
#define PP_REPEAT_75(m, d) PP_REPEAT_74(m, d) m(d, 74)
#define PP_REPEAT_76(m, d) PP_REPEAT_75(m, d) m(d, 75)
#define PP_REPEAT_77(m, d) PP_REPEAT_76(m, d) m(d, 76)
#define PP_REPEAT_78(m, d) PP_REPEAT_77(m, d) m(d, 77)
#define PP_REPEAT_79(m, d) PP_REPEAT_78(m, d) m(d, 78)
#define PP_REPEAT_80(m, d) PP_REPEAT_79(m, d) m(d, 79)
#define PP_REPEAT_81(m, d) PP_REPEAT_80(m, d) m(d, 80)
#define PP_REPEAT_82(m, d) PP_REPEAT_81(m, d) m(d, 81)
#define PP_REPEAT_83(m, d) PP_REPEAT_82(m, d) m(d, 82)
#define PP_REPEAT_84(m, d) PP_REPEAT_83(m, d) m(d, 83)
#define PP_REPEAT_85(m, d) PP_REPEAT_84(m, d) m(d, 84)
#define PP_REPEAT_86(m, d) PP_REPEAT_85(m, d) m(d, 85)
#define PP_REPEAT_87(m, d) PP_REPEAT_86(m, d) m(d, 86)
#define PP_REPEAT_88(m, d) PP_REPEAT_87(m, d) m(d, 87)
#define PP_REPEAT_89(m, d) PP_REPEAT_88(m, d) m(d, 88)
#define PP_REPEAT_90(m, d) PP_REPEAT_89(m, d) m(d, 89)
#define PP_REPEAT_91(m, d) PP_REPEAT_90(m, d) m(d, 90)
#define PP_REPEAT_92(m, d) PP_REPEAT_91(m, d) m(d, 91)
#define PP_REPEAT_93(m, d) PP_REPEAT_92(m, d) m(d, 92)
#define PP_REPEAT_94(m, d) PP_REPEAT_93(m, d) m(d, 93)
#define PP_REPEAT_95(m, d) PP_REPEAT_94(m, d) m(d, 94)
#define PP_REPEAT_96(m, d) PP_REPEAT_95(m, d) m(d, 95)
#define PP_REPEAT_97(m, d) PP_REPEAT_96(m, d) m(d, 96)
#define PP_REPEAT_98(m, d) PP_REPEAT_97(m, d) m(d, 97)
#define PP_REPEAT_99(m, d) PP_REPEAT_98(m, d) m(d, 98)

#define PP_REPEAT_EX(n, m, d, e) PP_CAT(PP_REPEAT_EX_, n)(m, d, e)
#define PP_REPEAT_EX_0(m, d, e)
#define PP_REPEAT_EX_1(m, d, e) m(d, 0, e)
#define PP_REPEAT_EX_2(m, d, e) PP_REPEAT_EX_1(m,  d, e) m(d, 1, e)
#define PP_REPEAT_EX_3(m, d, e) PP_REPEAT_EX_2(m,  d, e) m(d, 2, e)
#define PP_REPEAT_EX_4(m, d, e) PP_REPEAT_EX_3(m,  d, e) m(d, 3, e)
#define PP_REPEAT_EX_5(m, d, e) PP_REPEAT_EX_4(m,  d, e) m(d, 4, e)
#define PP_REPEAT_EX_6(m, d, e) PP_REPEAT_EX_5(m,  d, e) m(d, 5, e)
#define PP_REPEAT_EX_7(m, d, e) PP_REPEAT_EX_6(m,  d, e) m(d, 6, e)
#define PP_REPEAT_EX_8(m, d, e) PP_REPEAT_EX_7(m,  d, e) m(d, 7, e)
#define PP_REPEAT_EX_9(m, d, e) PP_REPEAT_EX_8(m,  d, e) m(d, 8, e)
#define PP_REPEAT_EX_10(m, d, e) PP_REPEAT_EX_9(m,  d, e) m(d, 9, e)
#define PP_REPEAT_EX_11(m, d, e) PP_REPEAT_EX_10(m, d, e) m(d, 10, e)
#define PP_REPEAT_EX_12(m, d, e) PP_REPEAT_EX_11(m, d, e) m(d, 11, e)
#define PP_REPEAT_EX_13(m, d, e) PP_REPEAT_EX_12(m, d, e) m(d, 12, e)
#define PP_REPEAT_EX_14(m, d, e) PP_REPEAT_EX_13(m, d, e) m(d, 13, e)
#define PP_REPEAT_EX_15(m, d, e) PP_REPEAT_EX_14(m, d, e) m(d, 14, e)
#define PP_REPEAT_EX_16(m, d, e) PP_REPEAT_EX_15(m, d, e) m(d, 15, e)
#define PP_REPEAT_EX_17(m, d, e) PP_REPEAT_EX_16(m, d, e) m(d, 16, e)
#define PP_REPEAT_EX_18(m, d, e) PP_REPEAT_EX_17(m, d, e) m(d, 17, e)
#define PP_REPEAT_EX_19(m, d, e) PP_REPEAT_EX_18(m, d, e) m(d, 18, e)
#define PP_REPEAT_EX_20(m, d, e) PP_REPEAT_EX_19(m, d, e) m(d, 19, e)
#define PP_REPEAT_EX_21(m, d, e) PP_REPEAT_EX_20(m, d, e) m(d, 20, e)
#define PP_REPEAT_EX_22(m, d, e) PP_REPEAT_EX_21(m, d, e) m(d, 21, e)
#define PP_REPEAT_EX_23(m, d, e) PP_REPEAT_EX_22(m, d, e) m(d, 22, e)
#define PP_REPEAT_EX_24(m, d, e) PP_REPEAT_EX_23(m, d, e) m(d, 23, e)
#define PP_REPEAT_EX_25(m, d, e) PP_REPEAT_EX_24(m, d, e) m(d, 24, e)
#define PP_REPEAT_EX_26(m, d, e) PP_REPEAT_EX_25(m, d, e) m(d, 25, e)
#define PP_REPEAT_EX_27(m, d, e) PP_REPEAT_EX_26(m, d, e) m(d, 26, e)
#define PP_REPEAT_EX_28(m, d, e) PP_REPEAT_EX_27(m, d, e) m(d, 27, e)
#define PP_REPEAT_EX_29(m, d, e) PP_REPEAT_EX_28(m, d, e) m(d, 28, e)
#define PP_REPEAT_EX_30(m, d, e) PP_REPEAT_EX_29(m, d, e) m(d, 29, e)
#define PP_REPEAT_EX_31(m, d, e) PP_REPEAT_EX_30(m, d, e) m(d, 30, e)
#define PP_REPEAT_EX_32(m, d, e) PP_REPEAT_EX_31(m, d, e) m(d, 31, e)
#define PP_REPEAT_EX_33(m, d, e) PP_REPEAT_EX_32(m, d, e) m(d, 32, e)
#define PP_REPEAT_EX_34(m, d, e) PP_REPEAT_EX_33(m, d, e) m(d, 33, e)
#define PP_REPEAT_EX_35(m, d, e) PP_REPEAT_EX_34(m, d, e) m(d, 34, e)
#define PP_REPEAT_EX_36(m, d, e) PP_REPEAT_EX_35(m, d, e) m(d, 35, e)
#define PP_REPEAT_EX_37(m, d, e) PP_REPEAT_EX_36(m, d, e) m(d, 36, e)
#define PP_REPEAT_EX_38(m, d, e) PP_REPEAT_EX_37(m, d, e) m(d, 37, e)
#define PP_REPEAT_EX_39(m, d, e) PP_REPEAT_EX_38(m, d, e) m(d, 38, e)
#define PP_REPEAT_EX_40(m, d, e) PP_REPEAT_EX_39(m, d, e) m(d, 39, e)
#define PP_REPEAT_EX_41(m, d, e) PP_REPEAT_EX_40(m, d, e) m(d, 40, e)
#define PP_REPEAT_EX_42(m, d, e) PP_REPEAT_EX_41(m, d, e) m(d, 41, e)
#define PP_REPEAT_EX_43(m, d, e) PP_REPEAT_EX_42(m, d, e) m(d, 42, e)
#define PP_REPEAT_EX_44(m, d, e) PP_REPEAT_EX_43(m, d, e) m(d, 43, e)
#define PP_REPEAT_EX_45(m, d, e) PP_REPEAT_EX_44(m, d, e) m(d, 44, e)
#define PP_REPEAT_EX_46(m, d, e) PP_REPEAT_EX_45(m, d, e) m(d, 45, e)
#define PP_REPEAT_EX_47(m, d, e) PP_REPEAT_EX_46(m, d, e) m(d, 46, e)
#define PP_REPEAT_EX_48(m, d, e) PP_REPEAT_EX_47(m, d, e) m(d, 47, e)
#define PP_REPEAT_EX_49(m, d, e) PP_REPEAT_EX_48(m, d, e) m(d, 48, e)
#define PP_REPEAT_EX_50(m, d, e) PP_REPEAT_EX_49(m, d, e) m(d, 49, e)
#define PP_REPEAT_EX_51(m, d, e) PP_REPEAT_EX_50(m, d, e) m(d, 50, e)
#define PP_REPEAT_EX_52(m, d, e) PP_REPEAT_EX_51(m, d, e) m(d, 51, e)
#define PP_REPEAT_EX_53(m, d, e) PP_REPEAT_EX_52(m, d, e) m(d, 52, e)
#define PP_REPEAT_EX_54(m, d, e) PP_REPEAT_EX_53(m, d, e) m(d, 53, e)
#define PP_REPEAT_EX_55(m, d, e) PP_REPEAT_EX_54(m, d, e) m(d, 54, e)
#define PP_REPEAT_EX_56(m, d, e) PP_REPEAT_EX_55(m, d, e) m(d, 55, e)
#define PP_REPEAT_EX_57(m, d, e) PP_REPEAT_EX_56(m, d, e) m(d, 56, e)
#define PP_REPEAT_EX_58(m, d, e) PP_REPEAT_EX_57(m, d, e) m(d, 57, e)
#define PP_REPEAT_EX_59(m, d, e) PP_REPEAT_EX_58(m, d, e) m(d, 58, e)
#define PP_REPEAT_EX_60(m, d, e) PP_REPEAT_EX_59(m, d, e) m(d, 59, e)
#define PP_REPEAT_EX_61(m, d, e) PP_REPEAT_EX_60(m, d, e) m(d, 60, e)
#define PP_REPEAT_EX_62(m, d, e) PP_REPEAT_EX_61(m, d, e) m(d, 61, e)
#define PP_REPEAT_EX_63(m, d, e) PP_REPEAT_EX_62(m, d, e) m(d, 62, e)
#define PP_REPEAT_EX_64(m, d, e) PP_REPEAT_EX_63(m, d, e) m(d, 63, e)
#define PP_REPEAT_EX_65(m, d, e) PP_REPEAT_EX_64(m, d, e) m(d, 64, e)
#define PP_REPEAT_EX_66(m, d, e) PP_REPEAT_EX_65(m, d, e) m(d, 65, e)
#define PP_REPEAT_EX_67(m, d, e) PP_REPEAT_EX_66(m, d, e) m(d, 66, e)
#define PP_REPEAT_EX_68(m, d, e) PP_REPEAT_EX_67(m, d, e) m(d, 67, e)
#define PP_REPEAT_EX_69(m, d, e) PP_REPEAT_EX_68(m, d, e) m(d, 68, e)
#define PP_REPEAT_EX_70(m, d, e) PP_REPEAT_EX_69(m, d, e) m(d, 69, e)
#define PP_REPEAT_EX_71(m, d, e) PP_REPEAT_EX_70(m, d, e) m(d, 70, e)
#define PP_REPEAT_EX_72(m, d, e) PP_REPEAT_EX_71(m, d, e) m(d, 71, e)
#define PP_REPEAT_EX_73(m, d, e) PP_REPEAT_EX_72(m, d, e) m(d, 72, e)
#define PP_REPEAT_EX_74(m, d, e) PP_REPEAT_EX_73(m, d, e) m(d, 73, e)
#define PP_REPEAT_EX_75(m, d, e) PP_REPEAT_EX_74(m, d, e) m(d, 74, e)
#define PP_REPEAT_EX_76(m, d, e) PP_REPEAT_EX_75(m, d, e) m(d, 75, e)
#define PP_REPEAT_EX_77(m, d, e) PP_REPEAT_EX_76(m, d, e) m(d, 76, e)
#define PP_REPEAT_EX_78(m, d, e) PP_REPEAT_EX_77(m, d, e) m(d, 77, e)
#define PP_REPEAT_EX_79(m, d, e) PP_REPEAT_EX_78(m, d, e) m(d, 78, e)
#define PP_REPEAT_EX_80(m, d, e) PP_REPEAT_EX_79(m, d, e) m(d, 79, e)
#define PP_REPEAT_EX_81(m, d, e) PP_REPEAT_EX_80(m, d, e) m(d, 80, e)
#define PP_REPEAT_EX_82(m, d, e) PP_REPEAT_EX_81(m, d, e) m(d, 81, e)
#define PP_REPEAT_EX_83(m, d, e) PP_REPEAT_EX_82(m, d, e) m(d, 82, e)
#define PP_REPEAT_EX_84(m, d, e) PP_REPEAT_EX_83(m, d, e) m(d, 83, e)
#define PP_REPEAT_EX_85(m, d, e) PP_REPEAT_EX_84(m, d, e) m(d, 84, e)
#define PP_REPEAT_EX_86(m, d, e) PP_REPEAT_EX_85(m, d, e) m(d, 85, e)
#define PP_REPEAT_EX_87(m, d, e) PP_REPEAT_EX_86(m, d, e) m(d, 86, e)
#define PP_REPEAT_EX_88(m, d, e) PP_REPEAT_EX_87(m, d, e) m(d, 87, e)
#define PP_REPEAT_EX_89(m, d, e) PP_REPEAT_EX_88(m, d, e) m(d, 88, e)
#define PP_REPEAT_EX_90(m, d, e) PP_REPEAT_EX_89(m, d, e) m(d, 89, e)
#define PP_REPEAT_EX_91(m, d, e) PP_REPEAT_EX_90(m, d, e) m(d, 90, e)
#define PP_REPEAT_EX_92(m, d, e) PP_REPEAT_EX_91(m, d, e) m(d, 91, e)
#define PP_REPEAT_EX_93(m, d, e) PP_REPEAT_EX_92(m, d, e) m(d, 92, e)
#define PP_REPEAT_EX_94(m, d, e) PP_REPEAT_EX_93(m, d, e) m(d, 93, e)
#define PP_REPEAT_EX_95(m, d, e) PP_REPEAT_EX_94(m, d, e) m(d, 94, e)
#define PP_REPEAT_EX_96(m, d, e) PP_REPEAT_EX_95(m, d, e) m(d, 95, e)
#define PP_REPEAT_EX_97(m, d, e) PP_REPEAT_EX_96(m, d, e) m(d, 96, e)
#define PP_REPEAT_EX_98(m, d, e) PP_REPEAT_EX_97(m, d, e) m(d, 97, e)
#define PP_REPEAT_EX_99(m, d, e) PP_REPEAT_EX_98(m, d, e) m(d, 98, e)
